# Generated by Django 2.2.24 on 2021-07-29 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_level', multiselectfield.db.fields.MultiSelectField(choices=[('1sp', '1. klasa s.p.'), ('2sp', '2. klasa s.p.'), ('3sp', '3. klasa s.p.'), ('4sp', '4. klasa s.p.'), ('5sp', '5. klasa s.p.'), ('6sp', '6. klasa s.p.'), ('7sp', '7. klasa s.p.'), ('8sp', '8. klasa s.p.'), ('1lic', '1. klasa lic/tech'), ('2lic', '2. klasa lic/tech'), ('3lic', '3. klasa lic/tech'), ('4lic', '4. klasa lic/tech'), ('5tech', '1. klasa tech')], max_length=57)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('subject', multiselectfield.db.fields.MultiSelectField(choices=[('pol', 'j. polski'), ('eng', 'j. angielski'), ('ger', 'j. niemiecki'), ('math', 'matematyka'), ('phi', 'fizyka'), ('bio', 'biologia')], max_length=24)),
                ('last_topics', models.TextField(blank=True, max_length=300, null=True)),
                ('planned_topics', models.TextField(blank=True, max_length=300, null=True)),
                ('need_substitution', models.BooleanField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teacher', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
