# Generated by Django 3.2.5 on 2021-07-06 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('subjects', multiselectfield.db.fields.MultiSelectField(choices=[('pol', 'j. polski'), ('eng', 'j. angielski'), ('ger', 'j. niemiecki'), ('math', 'matematyka'), ('phi', 'fizyka'), ('bio', 'biologia')], max_length=24)),
                ('lessons_taken', models.IntegerField()),
                ('lessons_cancelled', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
