//auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_STATE = 'RESET_STATE';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAIL = 'TOKEN_REFRESH_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFRIM_SUCCESS';
export const CHANGE_DEFAULT_PASSWORD_SUCCESS =
  'CHANGE_DEFAULT_PASSWORD_SUCCESS';
export const CHANGE_DEFAULT_PASSWORD_FAIL = 'CHANGE_DEFAULT_PASSWORD_FAIL';
export const LOGOUT = 'LOGOUT';

//errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAN_ERROR_MSG = 'CLEAN_ERROR_MSG';

//createSubstitutions
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAIL = 'GET_CLASSES_FAIL';

//analysis
export const GET_VOLUNTEER_ANALYSIS_SUCCESS = 'GET_VOLUNTEER_ANALYSIS_SUCCESS';
export const GET_VOLUNTEER_ANALYSIS_FAIL = 'GET_VOLUNTEER_ANALYSIS_FAIL';
export const GET_LECTURE_ANALYSIS_SUCCESS = 'GET_LECTURE_ANALYSIS_SUCCESS';
export const GET_LECTURE_ANALYSIS_FAIL = 'GET_LECTURE_ANALYSIS_FAIL';
