//auth:
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const RESET_STATE = 'RESET_STATE';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAIL = 'TOKEN_REFRESH_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFRIM_SUCCESS';
export const CHANGE_DEFAULT_PASSWORD_SUCCESS =
  'CHANGE_DEFAULT_PASSWORD_SUCCESS';
export const CHANGE_DEFAULT_PASSWORD_FAIL = 'CHANGE_DEFAULT_PASSWORD_FAIL';
export const LOGOUT = 'LOGOUT';

//errors:
export const GET_ERRORS = 'GET_ERRORS';

//createSubstitutions
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL';
export const GET_LEVEL_SUCCESS = 'GET_LEVEL_SUCCESS';
export const GET_LEVEL_FAIL = 'GET_LEVEL_FAIL';

//substitutions:
export const GET_PENDING_SUBSTITUTIONS_SUCCESS =
  'GET_PENDING_SUBSTITUTIONS_SUCCESS';
export const GET_PENDING_SUBSTITUTIONS_FAIL = 'GET_PENDING_SUBSTITUTIONS_FAIL';
export const GET_SUBSTITUTION_SUCCESS = 'GET_SUBSTITUTION_SUCCESS';
export const GET_SUBSTITUTION_FAIL = 'GET_SUBSTITUTION_FAIL';
export const GET_TAKEN_SUBSTITUTIONS_SUCCESS = "GET_TAKEN_SUBSTITUTIONS_SUCCESS"
export const GET_TAKEN_SUBSTITUTIONS_FAIL = "GET_TAKEN_SUBSTITUTIONS_FAIL"
export const ASSIGN_TEACHER_SUCCESS = 'ASSIGN_TEACHER_SUCCESS';
export const ASSIGN_TEACHER_FAIL = 'ASSIGN_TEACHER_FAIL';
export const CREATE_SUBSTITUTION_SUCCESS = 'CREATE_SUBSTITUTION_SUCCESS';
export const CREATE_SUBSTITUTION_FAIL = 'CREATE_SUBSTITUTION_FAIL';
export const MODIFY_SUBSTITUTION_SUCCESS = 'MODIFY_SUBSTITUTION_SUCCESS';
export const MODIFY_SUBSTITUTION_FAIL = 'MODIFY_SUBSTITUTION_FAIL';
export const DELETE_SUBSTITUTION_SUCCESS = 'DELETE_SUBSTITUTION_SUCCESS';
export const DELETE_SUBSTITUTION_FAIL = 'DELETE_SUBSTITUTION_FAIL';

