# Generated by Django 3.2.5 on 2021-07-08 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonModel',
            new_name='Lesson',
        ),
    ]
