name: Tests
on:
  push:
    paths-ignore:
      - '**.js'
    branches-ignore:
      - 'front/'
      - '**front**'

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install Python dependencies
      run: |
        sudo apt install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Test with pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        DEVELOP_DEBUG: ${{ secrets.DEVELOP_DEBUG }}
      run: |
        SECRET_KEY=$SECRET_KEY EMAIL_PWD=$EMAIL_PWD DEVELOP_DEBUG=$DEVELOP_DEBUG EMAIL_HOST=$EMAIL_HOST EMAIL_PORT=$EMAIL_PORT EMAIL_USER=$EMAIL_USER DATABASE_NAME=$DATABASE_NAME DATABASE_URL=$DATABASE_URL DATABASE_HOST=$DATABASE_HOST DATABASE_USER=$DATABASE_USER DATABASE_PWD=$DATABASE_PWD pytest --exitfirst --verbose --failed-first \

    - name: Build coverage file
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        DEVELOP_DEBUG: ${{ secrets.DEVELOP_DEBUG }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PWD: ${{ secrets.DATABASE_PWD }}
      run: |
        SECRET_KEY=$SECRET_KEY EMAIL_PWD=$EMAIL_PWD DEVELOP_DEBUG=$DEVELOP_DEBUG EMAIL_HOST=$EMAIL_HOST EMAIL_PORT=$EMAIL_PORT EMAIL_USER=$EMAIL_USER DATABASE_NAME=$DATABASE_NAME DATABASE_URL=$DATABASE_URL DATABASE_HOST=$DATABASE_HOST DATABASE_USER=$DATABASE_USER DATABASE_PWD=$DATABASE_PWD pytest --cache-clear --cov=backend --cov-report xml \
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: pytest
